# Generated by Django 4.2.7 on 2023-11-09 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro_app', '0003_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='Technologyname',
        ),
        migrations.AddField(
            model_name='topic',
            name='Technologyname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pro_app.technology'),
        ),
    ]
